<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Form\ProjectAddForm $form
 */

$form->setAttribute('action', $this->url('home/action', ['controller' => 'project', 'action' => 'add']));
$form->prepare();

$test = $form->get('mainpicture')->getMessages();

// debug
//echo '$test =';
//var_dump($test);


?>

<h1>proposer un projet</h1>

<?php

echo $this->form()->openTag($form);
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('subtitle'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('mainpicture'));
echo $this->formRow($form->get('deadline'));
echo $this->formRow($form->get('goal'));
echo $this->formRow($form->get('category_ids'));
echo $this->formRow($form->get('tag_ids'));
echo $this->formRow($form->get('picture_ids'));
echo $this->formSubmit($form->get('submit'));
?>

<p>* Champs obligatoires</p>

<?php
echo $this->form()->closeTag($form);

?>

<style>
	label {
		display : block;
	}
</style>
