<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array                           $createdProjectsData
 */

$this->headScript()
     ->appendFile('https://code.highcharts.com/highcharts.js')
     ->appendFile('http://code.highcharts.com/maps/modules/map.js')
     ->appendFile('https://code.highcharts.com/mapdata/countries/fr/fr-all-all.js')
     ->appendScript('
        var createdProjectsData = '.json_encode($createdProjectsData).';
        ')
     ->appendFile($this->basePath('js/project/analyse.js'));

$this->headLink()->appendStylesheet($this->basePath('css/transaction/analyse.min.css'));

?>

<h1>analyse des projets</h1>

<div id="createdProjects"></div>

<div id="transactions"></div>