<?php

/**
 * @var \Application\Model\Project      $project
 * @var \Application\Model\Category[]   $categories
 * @var \Application\Model\Gift[]       $gifts
 * @var integer                         $viewsCount
 * @var \Application\Model\Video[]      $videos
 * @var \Application\Model\Picture[]    $pictures
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Model\User[]       $financers
 */

// debug
//echo '$project =';
//var_dump($project);
//
//echo "categories:";
//foreach ($categories as $category)
//{
//	// debug
//	echo '$category =';
//	var_dump($category);
//}
//
//echo "gifts:";
//foreach ($gifts as $gift)
//{
//	// debug
//	echo '$gift =';
//	var_dump($gift);
//}
//
//echo "tags:";
//foreach ($tags as $tag)
//{
//	// debug
//	echo '$tag =';
//	var_dump($tag);
//}
//
//// debug
//echo '$viewsCount =';
//var_dump($viewsCount);
//
//echo '$videos:';
//var_dump($videos);
//foreach ($videos as $video)
//{
//	// debug
//	echo '$video =';
//	var_dump($video);
//}
//
//echo '$pictures:';
//foreach ($pictures as $picture)
//{
//	// debug
//	echo '$picture =';
//	var_dump($picture);
//}

$remainingDaysCount = $project->getRemainingDaysCount();

$timeLabel = $remainingDaysCount > 0 ? 'Jusqu\'au '.$project->getFormattedDeadLine() : 'terminé';

?>

<div class="subNav">
	<div class="row">
		<div class="col-xs-2 hidden-xs">
			<h1><?= $project->title ?></h1>
		</div>
		<div class="col-xs-12 col-sm-10">
			<ul class="list-inline">
				<li>
					<a href="#mainPicture" class="active">
						<i class="icomoon icon_pie"></i>
						<span>Résumé</span>
					</a>
				</li>
				<li>
					<a href="#description">
						<i class="icomoon icon_dots"></i>
						<span>Description</span>
					</a>
				</li>
				<li>
					<a href="#movies">
						<i class="icomoon icon_pictures"></i>
						<span>Images</span>
					</a>
				</li>
				<li>
					<a href="#gifts">
						<i class="icomoon icon_gift"></i>
						<span>Contreparties</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>

<div class="row offsetContainer">
	<div id="mainPicture" class="col-xs-12 col-md-8">
		<img class="img-responsive" src="<?= $project->mainpicture ?>" alt="Image principale - <?= $project->title ?>">
	</div>
	<div class="col-xs-12 col-md-8">
		<h2><?= $project->subtitle ?></h2>
	</div>
	<div id="stats" class="col-xs-12 col-md-4">
		<div class="row">
			<div class="col-xs-4 col-md-12">
				<div class="iconWrapper"><?= $this->partial('/partial/project/goal.phtml', ['project' => $project]) ?></div>
				<span><?= $project->transactionsum ?>&nbsp;/&nbsp;<?= $project->goal ?>&nbsp;€</span>
			</div>
			<div class="col-xs-4 col-md-12">
				<div class="iconWrapper"><?= $this->partial('/partial/project/remainingTime.phtml', ['project' => $project]) ?></div>
				<span><?= $timeLabel ?></span>
			</div>
			<div class="col-xs-4 col-md-12">
				<div class="iconWrapper">
					<i class="icomoon icon_people"></i>
				</div>
				<span><?= count($financers) ?></span>
			</div>
		</div>
	</div>
	<div id="description" class="col-xs-12 col-md-8">
		<?= $project->description ?>
	</div>
	<div id="movies" class="col-xs-12 col-md-8">
		<?php if (count($videos) > 0): ?>
			<div id="my_carousel" class="carousel slide" data-ride="carousel">
				<!-- Bulles -->
				<ol class="carousel-indicators">
					<?php for ($i=0; $i<count($videos); $i++): ?>
						<li data-target="#my_carousel" data-slide-to="<?= $i ?>" class="<?= $i === 0 ? 'active' : '' ?>"></li>
					<?php endfor; ?>
				</ol>
				<!-- Slides -->
				<div class="carousel-inner">
					<?php foreach ($videos as $i => $video): ?>
						<div class="item <?= $i === 0 ? 'active' : '' ?>">
							<div class="carousel-page">
								<video src="<?= $video->url ?>"></video>
							</div>
							<!--<div class="carousel-caption">Page 2 de présentation</div>-->
						</div>
					<?php endforeach; ?>
				</div>
				<!-- Contrôles -->
				<a class="left carousel-control" href="#my_carousel" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left"></span>
				</a>
				<a class="right carousel-control" href="#my_carousel" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right"></span>
				</a>
			</div>
		<?php else: ?>
			<?php foreach ($videos as $i => $video): ?>
				<video src="<?= $video->url ?>"></video>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
	<div id="pictures" class="col-xs-12 col-md-8">
		<?php foreach ($pictures as $picture): ?>
			<div class="picture">
				<img src="<?= $picture->url ?>">
			</div>
		<?php endforeach; ?>
	</div>
	<div id="gifts" class="col-xs-12 col-md-4">
		<?php foreach ($gifts as $gift): ?>
			<div class="gift">
				<p class="minAmount">
					<i class="icomoon icon_payment"></i>
					<span>&#62; <?= $gift->minamount ?> €</span>
				</p>
				<h3><?= $gift->title ?></h3>
				<p class="description">
					<?= $gift->description ?>
				</p>
			</div>
		<?php endforeach; ?>
	</div>
</div>
