<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Model\Project[]    $projects
 * @var array                           $editableProjectsIds
 */
use Application\Util\DateFormatter;

?>

<h1>mes projets</h1>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Titre</th>
        <th>Date de création</th>
        <th>Date de fin</th>
        <th>Objectif</th>
        <th>Somme obetnue</th>
        <th>Actions possibles</th>
    </tr>
    </thead>
    <tbody>
	<?php foreach ($projects as $project): ?>
        <tr>
            <td><?= $project->title ?></td>
            <td><?= DateFormatter::usToFr($project->creationdate) ?></td>
            <td><?= DateFormatter::usToFr($project->deadline) ?></td>
            <td><?= $project->goal ?>&nbsp;€</td>
            <td><?= $project->transactionsum ?>&nbsp;€ (<?= $project->getGoalReachingPercentage() ?>&nbsp;%)</td>
            <td>
                <div class="btn-group">
                    <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'detail', 'id' => $project->id]) ?>" class="btn btn-default" title="voir">
                        <i class="fa fa-eye"></i>
                        <span class="hidden-xs hidden-sm">voir</span>
                    </a>
					<?php if (in_array($project->id, $editableProjectsIds)): ?>
                        <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'user_update', 'id' => $project->id]) ?>" class="btn btn-default" title="éditer">
                            <i class="fa fa-pencil"></i>
                            <span class="hidden-xs hidden-sm">éditer</span>
                        </a>
                        <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'user_delete', 'id' => $project->id]) ?>" class="btn btn-default" title="supprimer">
                            <i class="fa fa-trash"></i>
                            <span class="hidden-xs hidden-sm">supprimer</span>
                        </a>
					<?php endif; ?>
					<?php if (!$project->deadLineIsPassed()): ?>
                        <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'user_promote', 'id' => $project->id]) ?>" class="btn btn-default" title="mettre en avant">
                            <i class="fa fa-thumbs-up"></i>
                            <span class="hidden-xs hidden-sm">mettre en avant</span>
                        </a>
					<?php endif; ?>
                    <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'export', 'id' => $project->id]) ?>" class="btn btn-default" title="exporter les informations des financeurs">
                        <i class="fa fa-download"></i>
                        <span class="hidden-xs hidden-sm">exporter les informations des financeurs</span>
                    </a>
                </div>
            </td>
        </tr>
	<?php endforeach; ?>
    </tbody>
</table>