<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Model\Project[]    $projects
 * @var array                           $editableProjectsIds
 */
use Application\Util\DateFormatter;

?>

<h1>mes projets</h1>
<table class="table">
    <thead>
    <tr>
        <th>Titre</th>
        <th>Date de création</th>
        <th>Date de fin</th>
        <th>Objectif</th>
        <th>Somme obetnue</th>
        <th>Actions possibles</th>
    </tr>
    </thead>
    <tbody>
	<?php foreach ($projects as $project): ?>
        <tr>
            <td><?= $project->title ?></td>
            <td><?= DateFormatter::usToFr($project->creationdate) ?></td>
            <td><?= DateFormatter::usToFr($project->deadline) ?></td>
            <td><?= $project->goal ?>&nbsp;€</td>
            <td><?= $project->transactionsum ?>&nbsp;€ (<?= $project->getGoalReachingPercentage() ?>&nbsp;%)</td>
            <td>
                <div class="btn-group">
                    <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'detail', 'id' => $project->id]) ?>" class="btn btn-default">voir</a>
					<?php if (in_array($project->id, $editableProjectsIds)): ?>
                        <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'user_update', 'id' => $project->id]) ?>" class="btn btn-default">éditer</a>
                        <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'user_delete', 'id' => $project->id]) ?>" class="btn btn-default">supprimer</a>
					<?php endif; ?>
					<?php if (!$project->deadLineIsPassed()): ?>
                        <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'user_promote', 'id' => $project->id]) ?>" class="btn btn-default">mettre en avant</a>
					<?php endif; ?>
                    <a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'export', 'id' => $project->id]) ?>" class="btn btn-default">exporter les informations des financeurs</a>
                </div>
            </td>
        </tr>
	<?php endforeach; ?>
    </tbody>
</table>