<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array[]                         $sexPieData
 * @var array[]                         $ageData
 * @var array[]                         $departmentData
 */

$this->headScript()
     ->appendFile('https://code.highcharts.com/highcharts.js')
     ->appendFile('http://code.highcharts.com/maps/modules/map.js')
     ->appendFile('https://code.highcharts.com/mapdata/countries/fr/fr-all-all.js')
     ->appendScript('
        var sexPieData = '.json_encode($sexPieData).';
        var ageData = '.json_encode($ageData).';
        var departmentData = '.json_encode($departmentData).';
        ')
     ->appendFile($this->basePath('js/transaction/analyse.min.js'));

$this->headLink()->appendStylesheet($this->basePath('css/transaction/analyse.min.css'));

?>

<h1>analyse des financeurs</h1>

<div id="sexPie"></div>

<div id="ageChart"></div>

<div id="departmentsMap"></div>