<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer  $this
 *
 * @var \Application\Model\Project       $project
 * @var \Application\Model\Paymentmethod $paymentMethod
 * @var integer                          $amount
 */
?>

<h1>Paiement</h1>

<p>montant: <?= $amount ?></p>
<p>projet: <?= $project->title ?></p>
<p>méthode de paiement: <?= $paymentMethod->name ?></p>

<form method="post" action="<?= $this->url('home/action', ['controller' => 'transaction', 'action' => 'add']) ?>">
	<input type="hidden" name="projectId" value="<?= $project->id ?>">
	<input type="hidden" name="paymentMethodId" value="<?= $paymentMethod->id ?>">
	<input type="hidden" name="amount" value="<?= $amount ?>">

	<input type="submit" value="simuler le paiement" class="btn btn-primary">
</form>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
	<input type="hidden" name="cmd" value="_donations">
	<input type="hidden" name="business" value="VKU9GPGJDSHM8">
	<input type="hidden" name="amount" value="<?= $amount ?>">
	<input type="hidden" name="currency_code" value="EUR">
	<input type="hidden" name="item_name" value="Financement du project <?= $project->title ?>">
	<input type="hidden" name="lc" value="fr_FR">
	<input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal, le réflexe sécurité pour payer en ligne">
	<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">

	<!-- callback is POST request including payment variables -->
	<input type="hidden" name="rm" value="2">
	<input type="hidden" name="notify_url" value="<?= $this->url('home/action', ['controller' => 'transaction', 'action' => 'paypal_callback']) ?>">
	<input type="hidden" name="return" value="<?= $this->url('home/action', ['controller' => 'transaction', 'action' => 'payment_success']) ?>">
	<input type="hidden" name="cbt" value="Revenir sur le site">
	<input type="hidden" name="cancel_return" value="<?= $this->url('home/action', ['controller' => 'transaction', 'action' => 'payment_cancel']) ?>">
</form>


