<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer|\Zend\View\Helper\Navigation\AbstractHelper $this
 */

?>

<?php echo $this->doctype(); ?>

<html lang="fr">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle($this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
	                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
	                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- styles -->
	<?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico'])
	                ->prependStylesheet($this->basePath('fonts/icomoon/style.css'))
	                ->prependStylesheet($this->basePath('css/style.css'))
	                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
	                ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

	<!-- scripts -->
	<?php echo $this->headScript()
	                ->prependFile($this->basePath('js/bootstrap.min.js'))
	                ->prependFile($this->basePath('js/jquery.min.js'))
	                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
	                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',]); ?>

</head>
<body>

<nav class="container-fluid">
	<div class="row">
		<div class="col-xs-2" id="logo">
			<a href="<?= $this->url('home') ?>">
				<img src="<?= $this->basePath('img/logo_md.png') ?>" alt="logo" class="visible-md visible-lg">
				<img src="<?= $this->basePath('img/logo_sm.png') ?>" alt="logo" class="visible-sm">
				<img src="<?= $this->basePath('img/logo_xs.png') ?>" alt="logo" class="visible-xs">
			</a>
		</div>
		<div class="col-xs-12 col-sm-10">
			<ul class="list-unstyled">
				<li>
					<a href="<?= $this->url('home/action', ['controller' => 'project', 'action' => 'add']) ?>">
						<img src="<?= $this->basePath('img/icon/nav_plus.png') ?>" alt="icône">
						<span>proposer une idée</span>
					</a>
				</li>
				<li>
					<a href="<?= $this->url('home/action', ['controller' => 'about', 'action' => 'index']) ?>">
						<img src="<?= $this->basePath('img/icon/nav_about.png') ?>" alt="icône">
						<span>à propos</span>
					</a>
				</li>
				<li>
					<a href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'index']) ?>">
						<img src="<?= $this->basePath('img/icon/nav_user.png') ?>" alt="icône">
						<span>mon compte</span>
					</a>
				</li>
				<li>
					<a href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'logout']) ?>">
						<img src="<?= $this->basePath('img/icon/nav_disconnect.png') ?>" alt="icône">
						<span>se déconnecter</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<div class="container-fluid" id="content">
	<?php echo $this->content; ?>
</div>
<footer>
	<img src="<?= $this->basePath('/img/logo_footer_reverse.png') ?>" alt="">
	<img src="<?= $this->basePath('/img/logo_footer.png') ?>" alt="">
	<p>&copy; 2016</p>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
