<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer|\Zend\View\Helper\Navigation\AbstractHelper $this
 */

use Application\Controller\UserController;

// try to get logged user
$user = null;
try
{
	$user = UserController::getLoggedUser();
}
catch (Exception $e)
{
}

?>

<?php echo $this->doctype(); ?>

<html lang="fr">
<head>
    <meta charset="utf-8">
    <!-- page title -->
	<?= $this->headTitle('Idées À Porter') ?>

    <!-- meta -->
	<?= $this->headMeta()
	         ->appendName('viewport', 'width=device-width, initial-scale=1.0')
	         ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

    <!-- icon -->
	<?= $this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath().'/img/favicon.png']) ?>

    <!-- dependencies -->
    <!-- global js variable -->
    <script>
        var _App = {
            rootUrl: '<?= $this->basePath() ?>'
        };
    </script>
	<?php

	// styles
	echo $this->headLink()
	          ->prependStylesheet($this->basePath('css/main.min.css'))
	          ->prependStylesheet($this->basePath('fonts/myriad_pro/myriad_pro.css'))
	          ->prependStylesheet($this->basePath('vendor/bower_components/basictable/basictable.css'))
	          ->prependStylesheet($this->basePath('vendor/bower_components/summernote/dist/summernote.css'))
	          ->prependStylesheet($this->basePath('vendor/bootstrap-tokenfield/dist/css/bootstrap-tokenfield.min.css'))
	          ->prependStylesheet($this->basePath('vendor/bootstrap-tokenfield/dist/css/tokenfield-typeahead.min.css'))
	          ->prependStylesheet($this->basePath('vendor/intl-tel-input-7.1.0/build/css/intlTelInput.css'))
	          ->prependStylesheet($this->basePath('vendor/bootstrap-fileinput-master/css/fileinput.min.css'))
	          ->prependStylesheet($this->basePath('vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css'))
	          ->prependStylesheet($this->basePath('vendor/bower_components/fontawesome/css/font-awesome.min.css'))
	          ->prependStylesheet($this->basePath('vendor/bootstrap/dist/css/bootstrap.min.css'));

	// scripts
	echo $this->headScript()
	          ->prependFile($this->basePath('js/main.min.js'))
	          ->prependFile($this->basePath('vendor/bower_components/basictable/jquery.basictable.min.js'))
	          ->prependFile($this->basePath('vendor/bower_components/summernote/dist/lang/summernote-fr-FR.min.js'))
	          ->prependFile($this->basePath('vendor/bower_components/summernote/dist/summernote.min.js'))
	          ->prependFile($this->basePath('vendor/bower_components/jquery-validate/dist/jquery.validate.min.js'))
	          ->prependFile($this->basePath('vendor/bower_components/moment/min/moment-with-locales.min.js'))
	          ->prependFile($this->basePath('vendor/jquery-scrollspy-master/scrollspy.js'))
	          ->prependFile($this->basePath('vendor/bootstrap-tokenfield/dist/bootstrap-tokenfield.min.js'))
	          ->prependFile($this->basePath('vendor/bootstrap-tokenfield/docs-assets/js/typeahead.bundle.min.js'))
	          ->prependFile($this->basePath('vendor/intl-tel-input-7.1.0/build/js/intlTelInput.min.js'))
	          ->prependFile($this->basePath('vendor/bootstrap-fileinput-master/js/locales/fr.js'))
	          ->prependFile($this->basePath('vendor/bootstrap-fileinput-master/js/fileinput.min.js'))
	          ->prependFile($this->basePath('vendor/bootstrap-datepicker/locales/bootstrap-datepicker.fr.min.js'))
	          ->prependFile($this->basePath('vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js'))
	          ->prependFile($this->basePath('vendor/bootstrap/dist/js/bootstrap.min.js'))
	          ->prependFile($this->basePath('vendor/jquery.min.js'));
	?>
</head>
<body>

<nav>
    <div class="container-fluid max-width-lg">
        <div class="row">
            <div class="col-xs-2" id="logo">
                <a href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/logo_md.png') ?>" alt="logo" class="visible-md visible-lg">
                    <img src="<?= $this->basePath('img/logo_sm.png') ?>" alt="logo" class="visible-sm">
                    <img src="<?= $this->basePath('img/logo_xs.png') ?>" alt="logo" class="visible-xs">
                </a>
            </div>
            <div class="col-xs-12 col-sm-10">
                <ul class="list-unstyled">
                    <li>
						<?php if (isset($user) && $user->isCreator()): ?>
                            <a href="<?= $this->url('home/action', ['controller' => 'project', 'action' => 'add']) ?>">
                                <i class="icomoon icon_plus"></i>
                                <span>proposer une idée</span>
                            </a>
						<?php endif; ?>
                    </li>
                    <li>
                        <a href="<?= $this->url('home/action', ['controller' => 'about', 'action' => 'index']) ?>">
                            <i class="icomoon icon_question"></i>
                            <span>à propos</span>
                        </a>
                    </li>
                    <li>
						<?php if (isset($user)):
							$userType = '';
							if ($user->isFinancer()) $userType = 'Financeur';
							elseif ($user->isCreator()) $userType = 'Créateur';
							elseif ($user->isAdmin()) $userType = 'Administrateur';
							?>
                            <a href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'index']) ?>">
                                <i class="icomoon icon_profile"></i>
                                <span>mon compte</span>
                            </a>
						<?php else: ?>
                            <a href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'signin']) ?>">
                                <i class="icomoon icon_profile_add"></i>
                                <span>créer un compte</span>
                            </a>
						<?php endif; ?>
                    </li>
                    <li>
						<?php if (isset($user)): ?>
                            <a href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'logout']) ?>">
                                <i class="icomoon icon_logout"></i>
                                <span>se déconnecter</span>
                            </a>
						<?php else: ?>
                            <a href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'login']) ?>">
                                <i class="icomoon icon_power"></i>
                                <span>se connecter</span>
                            </a>
						<?php endif; ?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="container-fluid max-width-lg" id="content">
	<?= $this->content; ?>
</div>
<footer>
    <img src="<?= $this->basePath('/img/logo_footer_reverse.png') ?>" alt="">
    <img src="<?= $this->basePath('/img/logo_footer.png') ?>" alt="">
    <p>&copy; 2016 - <a href="<?= $this->url('home/action', ['controller' => 'about', 'action' => 'legal']) ?>">mentions légales</a></p>
</footer>
<?= $this->inlineScript() ?>
</body>
</html>
