<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer|\Zend\View\Helper\Navigation\AbstractHelper $this
 */

?>

<?php echo $this->doctype(); ?>

<html lang="fr">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle($this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
	                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
	                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico'])
	                ->prependStylesheet($this->basePath('css/style.css'))
	                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
	                ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
	                ->prependFile($this->basePath('js/bootstrap.min.js'))
	                ->prependFile($this->basePath('js/jquery.min.js'))
	                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
	                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',]); ?>

</head>
<body>
<div class="container-fluid">
	<nav>
		<div class="row">
			<div class="col-xs-2" id="logo">
				<img src="<?= $this->basePath('img/logo_md.png') ?>" alt="logo" class="visible-md visible-lg">
				<img src="<?= $this->basePath('img/logo_sm.png') ?>" alt="logo" class="visible-sm">
				<img src="<?= $this->basePath('img/logo_xs.png') ?>" alt="logo" class="visible-xs">
			</div>
			<div class="col-xs-12 col-sm-10">
				<ul class="list-unstyled">
					<li>
						<a href="<?= $this->basePath('#') ?>">
							<img src="<?= $this->basePath('img/icon/nav_plus.png') ?>" alt="icône">
							<span>proposer une idée</span>
						</a>
					</li>
					<li>
						<a href="<?= $this->basePath('#') ?>">
							<img src="<?= $this->basePath('img/icon/nav_about.png') ?>" alt="icône">
							<span>à propos</span>
						</a>
					</li>
					<li>
						<a href="<?= $this->basePath('#') ?>">
							<img src="<?= $this->basePath('img/icon/nav_user.png') ?>" alt="icône">
							<span>mon compte</span>
						</a>
					</li>
					<li>
						<a href="<?= $this->basePath('#') ?>">
							<img src="<?= $this->basePath('img/icon/nav_disconnect.png') ?>" alt="icône">
							<span>se déconnecter</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div id="content">
		<?php echo $this->content; ?>
	</div>
	<footer>
		<p>&copy; 2016 - IDÉES À PORTER</p>
	</footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
