<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Model\Project      $project
 */

$goalReachingPercentage = $project->getGoalReachingPercentage();
$percentage             = $goalReachingPercentage > 100 ? 100 : $goalReachingPercentage;

$index = floor($percentage / 25) + 1;
if ($percentage < 100 / 3) $index = 1;
elseif ($percentage < 100 / 2) $index = 2;
elseif ($percentage < 100) $index = 3;
else  $index = 4;

?>

<i title="objectif atteint à <?= $goalReachingPercentage ?>%" class="icomoon icon_idea_<?= $index ?>" data-toggle="tooltip" data-placement="top auto">
    <span class="path1"></span>
    <span class="path2"></span>
</i>
