<?php
/**
 * @var \Application\Model\Project[] $projects
 */
?>

<?php foreach ($projects as $project): ?>
	<a href="<?= $this->url('home/action/id', ['controller' => 'project', 'action' => 'detail', 'id' => $project->id]) ?>" class="col-xs-12 col-sm-6 col-md-4 project">
		<?= $this->partial('/partial/project/cover.phtml', ['project' => $project]) ?>
		<h1><?= $project->title ?></h1>
		<h2><?= $project->subtitle ?></h2>
		<div class="row">
			<div class="col-xs-6 projectInfo projectGoal">
				<?= $this->partial('/partial/project/goal.phtml', ['project' => $project]) ?>
				<span><?= $project->goal ?> €</span>
			</div>
			<div class="col-xs-6 projectInfo projectRemainingTime">
				<?= $this->partial('/partial/project/remainingTime.phtml', ['project' => $project]) ?>
				<span>
					<?php
					$remainingDaysCount = $project->getRemainingDaysCount();
					if ($remainingDaysCount > 0)
					{
						echo 'J - '.$remainingDaysCount;
					}
					else
					{
						echo 'terminé';
					}
					?>
				</span>
			</div>
		</div>
		<hr class="horizontalSeparator">
	</a>
<?php endforeach; ?>