<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Model\Project      $project
 */

$remainingDays = $project->getRemainingDaysCount();

if ($remainingDays === 0)
{
	$index = 4;
}
elseif ($remainingDays < 10)
{
	$index = 3;
}
elseif ($remainingDays < 20)
{
	$index = 2;
}
else
{
	$index = 1;
}

?>

<i title="<?= $remainingDays ?> jours restants" class="icomoon icon_time_<?= $index ?>">
    <span class="path1"></span>
    <span class="path2"></span>
    <span class="path3"></span>
</i>