<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Model\Project      $project
 */

$remainingDays = $project->getRemainingDaysCount();

if ($remainingDays < 15)
{
	$index = 1;
}
elseif ($remainingDays < 30)
{
	$index = 2;
}
elseif ($remainingDays < 45)
{
	$index = 3;
}
else
{
	$index = 4;
}

?>

<i title="<?= $remainingDays ?> jours restants" class="icomoon icon_time_<?= $index ?>">
    <span class="path1"></span>
    <span class="path2"></span>
    <span class="path3"></span>
</i>