<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer      $this
 * @var \Application\Form\ChangePasswordForm $form
 */

use Application\Form\ChangePasswordForm;

$form->prepare();

?>

    <h1>Changer mon mot de passe</h1>

<?php

echo $this->form()->openTag($form);
echo $this->formRow($form->get(ChangePasswordForm::PASSWORD));
echo $this->formRow($form->get(ChangePasswordForm::PASSWORD_CONFIRM));
echo $this->formSubmit($form->get(ChangePasswordForm::SUBMIT));
?>

    <p>* Champs obligatoires</p>

<?php
echo $this->form()->closeTag($form);