<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer      $this
 * @var \Application\Form\ForgotPasswordForm $form
 */

use Application\Form\ForgotPasswordForm;

$form->prepare();

?>

    <h1>récupérer mon mot de passe</h1>

<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get(ForgotPasswordForm::EMAIL));
echo $this->formSubmit($form->get(ForgotPasswordForm::SUBMIT));
?>

    <p>* Champs obligatoires</p>

<?php
echo $this->form()->closeTag($form);