<?php

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Model\User $user
 */

// debug
//echo '$user =';
//var_dump($user);


?>

<h1>mon compte</h1>
<?php if ($user->isCreator()): ?>
	<a class="btn btn-primary" href="<?= $this->url('home/action', ['controller' => 'project', 'action' => 'user']) ?>">Mes projets</a>
<?php else: ?>
	<a class="btn btn-primary" href="<?= $this->url('home', ['controller' => 'transaction']) ?>">Mes financements</a>
<?php endif; ?>
<a class="btn btn-warning" href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'update']) ?>">Modifier mes informations</a>
<a class="btn btn-warning" href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'delete']) ?>">Supprimer mon compte</a>
