<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\Form\LoginForm     $form
 * @var string                          $facebookLoginUrl
 */

use Application\Form\LoginForm;

$form->prepare();

?>

<h1>Se connecter</h1>

<?php

echo $this->form()->openTag($form);
echo $this->formRow($form->get(LoginForm::EMAIL));
echo $this->formRow($form->get(LoginForm::PASSWORD));
echo $this->formSubmit($form->get(LoginForm::SUBMIT));
?>

<p>* Champs obligatoires</p>

<?php
echo $this->form()->closeTag($form);
?>

<div>
    <a href="<?= $this->url('home/action', ['controller' => 'user', 'action' => 'forgot_password']) ?>" class="btn btn-warning">J'ai oublié mon mot de passe</a>
</div>
<div>
    <a id="loginWithFacebookBtn" href="<?= $facebookLoginUrl ?>" class="btn btn-default">Se connecter avec facebook</a>
</div>
