<?php
/**
 * @var \Application\Form\UserForm $form
 */

use Application\Form\UserForm;

$form->setAttribute('action', $_SERVER['REQUEST_URI']);
$form->prepare();

?>

	<h1>Créer un compte</h1>

<?php

echo $this->form()->openTag($form);
echo $this->formRow($form->get(UserForm::USERTYPE_ID));
echo $this->formRow($form->get(UserForm::EMAIL));
echo $this->formRow($form->get(UserForm::PASSWORD));
echo $this->formRow($form->get(UserForm::NAME));
echo $this->formRow($form->get(UserForm::FIRSTNAME));
echo $this->formRow($form->get(UserForm::BIRTHDATE));
echo $this->formRow($form->get(UserForm::SEX));
echo $this->formRow($form->get(UserForm::ADRESS));
echo $this->formRow($form->get(UserForm::POSTCODE));
echo $this->formRow($form->get(UserForm::CITY));
echo $this->formRow($form->get(UserForm::COUNTRY_ID));
echo $this->formRow($form->get(UserForm::PHONE));
echo $this->formRow($form->get(UserForm::PHOTO));
echo $this->formRow($form->get(UserForm::FAVOURITECATEGORY_ID));
echo $this->formSubmit($form->get(UserForm::SUBMIT));
?>

	<p>* Champs obligatoires</p>

<?php
echo $this->form()->closeTag($form);