<?php
/**
 * @var \Application\Form\UserForm $form
 * @var \Application\Model\User    $user
 */

use Application\Form\UserForm;

$form->setAttribute('action', $_SERVER['REQUEST_URI']);
$form->prepare();

?>

	<h1>Modifier mon compte</h1>

<?php

echo $this->form()->openTag($form);
echo $this->formRow($form->get(UserForm::SEX));
echo $this->formRow($form->get(UserForm::ADRESS));
echo $this->formRow($form->get(UserForm::POSTCODE));
echo $this->formRow($form->get(UserForm::CITY));
echo $this->formRow($form->get(UserForm::COUNTRY_ID));
echo $this->formRow($form->get(UserForm::PHONE));
if ($user->isFinancer())
{
	echo $this->formRow($form->get(UserForm::FAVOURITECATEGORY_ID));
}
echo $this->formSubmit($form->get(UserForm::SUBMIT));
?>

	<p>* Champs obligatoires</p>

<?php
echo $this->form()->closeTag($form);