<?php
/**
 * @var \Application\Form\UserAddForm $form
 * @var \Application\Model\User       $user
 */

use Application\Form\UserAddForm;

$form->setAttribute('action', $_SERVER['REQUEST_URI']);
$form->prepare();

?>

	<h1>Modifier mon compte</h1>

<?php

echo $this->form()->openTag($form);
echo $this->formRow($form->get(UserAddForm::PASSWORD));
echo $this->formRow($form->get(UserAddForm::SEX));
echo $this->formRow($form->get(UserAddForm::ADRESS));
echo $this->formRow($form->get(UserAddForm::POSTCODE));
echo $this->formRow($form->get(UserAddForm::CITY));
echo $this->formRow($form->get(UserAddForm::COUNTRY_ID));
echo $this->formRow($form->get(UserAddForm::PHONE));
if ($user->isFinancer())
{
	echo $this->formRow($form->get(UserAddForm::FAVOURITECATEGORY_ID));
}
echo $this->formSubmit($form->get(UserAddForm::SUBMIT));
?>

	<p>* Champs obligatoires</p>

<?php
echo $this->form()->closeTag($form);